"""empty message

Revision ID: 41a892c87006
Revises: c53643087b1e
Create Date: 2019-01-31 12:01:30.357000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a892c87006'
down_revision = 'c53643087b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'admins_admin_password_key', 'admins', type_='unique')
    op.drop_constraint(u'users_user_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_user_password_key', 'users', ['user_password'])
    op.create_unique_constraint(u'admins_admin_password_key', 'admins', ['admin_password'])
    # ### end Alembic commands ###
